---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
      - name: php
        image: yamaszone/php7-lumen:7.1-fpm-alpine
        ports:
        - containerPort: 9000
        env:
          - name: DB_CONNECTION
            value: pgsql
          - name: DB_HOST
            value: postgres
          - name: DB_PORT
            value: "5432"
          - name: DB_DATABASE
            value: lumen_db
          - name: DB_USERNAME
            value: lumen
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: pgpass
                key: password
        resources:
          limits:
            memory: "500Mi"
            cpu: "200m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: yamaszone/nginx:1.13-alpine
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Secret
metadata:
  name: pgpass
  labels:
    "httpbin.org/example": lumen
type: Opaque
data:
  # echo -n lumen5432 | base64
  password: bHVtZW41NDMy
---
kind: Service
apiVersion: v1
metadata:
  name: php
  namespace: default
  labels:
    app: php
spec:
  ports:
  - name: listener
    protocol: TCP
    port: 9000
    targetPort: 9000
  selector:
    app: php
  sessionAffinity: None
---
kind: Service
apiVersion: v1
metadata:
  name: nginx
  namespace: default
  labels:
    app: nginx
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: nginx
  #type: NodePort
  # Use LoadBalancer type if supported by the cloud provider
  type: LoadBalancer
  sessionAffinity: None
